 export const dropTableHead = {
    'DropsTableHead': 'ObjetoLargadoCabeçalho',
    'DropsTableHead\\d+': 'ObjetoLargadoCabeçalho',
    'DropsLine': 'ObjetoLargado',
    'DropsLineSpiritGems': 'ObjetoLargadoGemasEspirituais',
    'DropsLineTriskelion': 'ObjetoLargadoTríscele',
    'DropsLineGhosts': 'ObjetoLargadoFantasmas',
    'DropsLineRW': 'ObjetoLargadoRecompensas',
    'Universal drops': 'ObjetoLargadoUniversal',
    'DropsLineArch': 'ObjetoLargadoArq',
    'DropsLineThiev': 'ObjetoLargadoRoubo',
    'DropsLineHunt': 'ObjetoLargadoCaça',
    'name': 'nome',
    'namenotes': 'nomeNotas',
    'quantity': 'quantidade',
    'quantitynotes': 'quantidadeNotas',
    'rarity': 'raridade',
    'raritynotes': 'raridadeNotas',
    'members': 'membros',
    'image': 'imagem',
    'version': 'ver',
    'noted': 'notas',
    'always': 'sempre',
    'common': 'comum',
    'uncommon': 'incomum',
    'rare': 'raro',
    'very rare': 'muito raro',
    'varies': 'varia',
    'random': 'aleatório',
    'unknown': 'desconhecido',
    'raritynotes': 'raridadeNotas',
    'alch\\s*=\\s*yes': 'alq = sim',
    'alch\\s*=\\s*no': 'alq = não',
    'AltCurrency': `moedaAlt`,
    'gemw\\s*=\\s*no': `mercado = não`,
    'gemw\\s*=\\s*yes': `mercado = sim`,
    'DropsTableBottom': `ObjetoLargadoRodapé`,
    'DropsTableBottom\d+': `ObjetoLargadoRodapé`,
    'DropsLineEnd': 'ObjetoLargadoRodapé',
    'Main Drop': 'Objetos principais',

    // Vai ter um outro objeto, não vai ficar tudo junto, mas vou deixar aqui por hora, depois crio um botão que altera o parametro usado
    
    'infobox item': 'Infobox objeto',
    'yes': 'Sim',
    'no': 'Não',
    'release': 'lançamento',
    'update': 'atualização',
    'quest': 'missão',
    'tradeable': 'negociável',
    'stackable': 'acumulável',
    'equipable': 'equipável',
    'value': 'valor',
    'disassembly': 'desmontável',
    'noteable': 'cupom',
    'actions': 'ações',
    'actions_equipped': 'ações_equipado',
    // Tenho que ver as ações pra adicionar aqui
    'destroy': 'destruir',
    'drop': 'largar',
    // Tenho que ver os itens presentes em destruir
    'kept': 'em morte',
    'reclaimable': 'recuperável',
    // Ver os itens presentes em kept
    'exchange': 'gemw',
    'examine': 'examinar',
    'weight': 'peso'
};